<?php
// seed_iluminacao.php — Insere blocos e cenas da aba Iluminação
$dsn  = 'mysql:host=localhost;dbname=SEU_BANCO;charset=utf8mb4';
$user = 'SEU_USUARIO';
$pass = 'SUA_SENHA';
try { $pdo = new PDO($dsn, $user, $pass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]); }
catch (Exception $e) { die('Erro de conexão: ' . $e->getMessage()); }
$tipoAba = 'iluminacao';
function upsert_bloco($pdo,$titulo,$icone,$tipoAba,$ordem){
  $q=$pdo->prepare('SELECT id FROM blocos WHERE titulo=? AND tipo_aba=? LIMIT 1');
  $q->execute([$titulo,$tipoAba]); $r=$q->fetch(PDO::FETCH_ASSOC);
  if($r){ $id=(int)$r['id']; $u=$pdo->prepare('UPDATE blocos SET icone=?, ordem_exibicao=?, ativo=1 WHERE id=?'); $u->execute([$icone,$ordem,$id]); return $id; }
  $i=$pdo->prepare('INSERT INTO blocos(titulo,icone,tipo_aba,ordem_exibicao,ativo) VALUES (?,?,?,?,1)');
  $i->execute([$titulo,$icone,$tipoAba,$ordem]); return (int)$pdo->lastInsertId(); }
function upsert_cena($pdo,$bloco,$titulo,$sub,$prompt,$valor,$ordem){
  $q=$pdo->prepare('SELECT id FROM cenas WHERE bloco_id=? AND (valor_selecao=? OR titulo=?) LIMIT 1');
  $q->execute([$bloco,$valor,$titulo]); $r=$q->fetch(PDO::FETCH_ASSOC);
  if($r){ $id=(int)$r['id']; $u=$pdo->prepare('UPDATE cenas SET subtitulo=?, texto_prompt=?, valor_selecao=?, ordem_exibicao=?, ativo=1 WHERE id=?'); $u->execute([$sub,$prompt,$valor,$ordem,$id]); return $id; }
  $i=$pdo->prepare('INSERT INTO cenas(bloco_id,titulo,subtitulo,texto_prompt,valor_selecao,ordem_exibicao,ativo) VALUES (?,?,?,?,?,?,1)');
  $i->execute([$bloco,$titulo,$sub,$prompt,$valor,$ordem]); return (int)$pdo->lastInsertId(); }
try{ $pdo->beginTransaction();
  $blc=upsert_bloco($pdo,'Natural','wb_sunny',$tipoAba,1);
  upsert_cena($pdo,$blc,'Golden Hour','Luz dourada suave','luz natural dourada de golden hour, sombras longas e quentes','golden_hour',1);
  upsert_cena($pdo,$blc,'Blue Hour','Crepúsculo azulado','luz natural azulada do blue hour, atmosfera serena','blue_hour',2);
  upsert_cena($pdo,$blc,'Amanhecer Suave','Início do dia','luz de amanhecer suave com névoa leve','amanhecer_suave',3);
  upsert_cena($pdo,$blc,'Meio-dia','Sol a pino intenso','luz natural dura de meio-dia com sombras curtas','meio_dia',4);
  upsert_cena($pdo,$blc,'Tarde Dourada','Quente e confortável','luz de tarde dourada com tonalidade quente','tarde_dourada',5);
  upsert_cena($pdo,$blc,'Luar Noturno','Clarão lunar','luz fria do luar com sombras sutis','luar_noturno',6);
  upsert_cena($pdo,$blc,'Céu Nublado Difuso','Soft natural','luz natural difusa de céu nublado, sem sombras marcadas','ceu_nublado_difuso',7);
  upsert_cena($pdo,$blc,'Neblina Leitosa','Difusão pesada','luz filtrada por neblina espessa, contraste reduzido','neblina_leitosa',8);
  upsert_cena($pdo,$blc,'Céu Tempestuoso','Drama natural','luz dramática sob nuvens carregadas e aberturas ocasionais','ceu_tempestuoso',9);
  upsert_cena($pdo,$blc,'Alpenglow','Montanhas rosadas','brilho rosado pós-pôr do sol nas montanhas (alpenglow)','alpenglow',10);
  upsert_cena($pdo,$blc,'God Rays Naturais','Feixes solares','feixes de luz solar atravessando nuvens/árvores com poeira','god_rays_naturais',11);
  upsert_cena($pdo,$blc,'Contraluz Solar','Silhuetas naturais','contraluz natural com o sol atrás do sujeito','contraluz_solar',12);
  upsert_cena($pdo,$blc,'Reflexo d’Água','Rebatida natural','luz refletida da água criando padrões móveis','reflexo_agua',13);
  upsert_cena($pdo,$blc,'Sombra de Folhagens','Dappled light','manchas de luz filtradas por folhagens','sombra_folhagens',14);
  upsert_cena($pdo,$blc,'Arco-íris','Fenômeno difrativo','presença de arco-íris iluminando a cena','arco_iris',15);
  upsert_cena($pdo,$blc,'Neve Brilhante','Albedo alto','luz rebatida pela neve, ambiente muito claro','neve_brilhante',16);
  $blc=upsert_bloco($pdo,'Artificial','lightbulb',$tipoAba,2);
  upsert_cena($pdo,$blc,'Neon Cyberpunk','Luzes coloridas vibrantes','neons saturados magenta/ciano criando reflexos molhados','neon_cyberpunk',1);
  upsert_cena($pdo,$blc,'LED Frio','Branco azulado','luz de LED fria com temperatura alta (6000–7000K)','led_frio',2);
  upsert_cena($pdo,$blc,'LED Quente','Tom aconchegante','luz de LED quente (2700–3200K) com tom amarelado','led_quente',3);
  upsert_cena($pdo,$blc,'Tungstênio Quente','Amarelo aconchegante','tungstênio 3200K com tom âmbar','tungstenio_quente',4);
  upsert_cena($pdo,$blc,'Fluorescente Verde','Hospitalar','luz fluorescente com leve dominante verde','fluorescente_verde',5);
  upsert_cena($pdo,$blc,'Halógeno Nítido','Spot claro','luz halógena com boa reprodução de cor','halogeno_nitido',6);
  upsert_cena($pdo,$blc,'Incandescente Vintage','Edison','lâmpada incandescente edison âmbar visível','incandescente_vintage',7);
  upsert_cena($pdo,$blc,'Blacklight UV','Ultravioleta','iluminação UV realçando materiais fluorescentes','blacklight_uv',8);
  upsert_cena($pdo,$blc,'Vapor de Sódio','Rua alaranjada','lâmpadas de vapor de sódio criando tom laranja urbano','vapor_sodio',9);
  upsert_cena($pdo,$blc,'Vapor de Mercúrio','Azulado antigo','lâmpadas de mercúrio com tonalidade azul-esverdeada','vapor_mercurio',10);
  upsert_cena($pdo,$blc,'Letreiro Neon Vintage','Retro glow','letreiros neon antigos com brilho suave','neon_vintage',11);
  upsert_cena($pdo,$blc,'RGB Ambiente Gamer','Color wash','wash RGB em paredes/teclados estilo setup gamer','rgb_gamer',12);
  upsert_cena($pdo,$blc,'Luz de Projetor','Cone visível','feixe de projetor com partículas no ar','luz_projetor',13);
  upsert_cena($pdo,$blc,'Strobo Festa','Flashes intermitentes','strobe rápido criando congelamento de movimento','strobo_festa',14);
  upsert_cena($pdo,$blc,'Laser Show','Feixes precisos','feixes de laser varrendo a cena com fumaça','laser_show',15);
  upsert_cena($pdo,$blc,'Painel Soft LED','Difuso e uniforme','painel LED com difusor grande e luz uniforme','painel_soft_led',16);
  upsert_cena($pdo,$blc,'Ring Light','Retrato','ring light criando catchlight circular nos olhos','ring_light',17);
  upsert_cena($pdo,$blc,'Lanternas de Papel','Suavidade quente','lanternas de papel amarelas penduradas','lanternas_papel',18);
  $blc=upsert_bloco($pdo,'Cinematográfica','movie_creation',$tipoAba,3);
  upsert_cena($pdo,$blc,'Three Point','Configuração clássica','key + fill + backlight equilibrados','three_point',1);
  upsert_cena($pdo,$blc,'High Key','Iluminação clara','altíssima luz, sombras suaves e contraste baixo','high_key',2);
  upsert_cena($pdo,$blc,'Low Key','Sombras dramáticas','grande contraste, predominância de sombras','low_key',3);
  upsert_cena($pdo,$blc,'Contra-luz','Silhueta rimada','backlight forte gerando silhueta e rim light','contra_luz',4);
  upsert_cena($pdo,$blc,'Rembrandt','Triângulo de luz','triângulo de luz na bochecha oposta','rembrandt',5);
  upsert_cena($pdo,$blc,'Butterfly/Paramount','Sombra borboleta','luz frontal e alta criando sombra sob o nariz','butterfly_paramount',6);
  upsert_cena($pdo,$blc,'Split Light','Metade iluminada','metade do rosto em luz, metade em sombra','split_light',7);
  upsert_cena($pdo,$blc,'Loop Light','Sombra pequena','sombra do nariz forma pequeno loop na bochecha','loop_light',8);
  upsert_cena($pdo,$blc,'Edge/Rim Light','Contorno','luz de recorte delineando as bordas do sujeito','rim_light',9);
  upsert_cena($pdo,$blc,'Top Light','De cima','luz superior teatral com sombras oculares','top_light',10);
  upsert_cena($pdo,$blc,'Underlight','De baixo (terror)','luz vinda de baixo criando efeito inquietante','underlight',11);
  upsert_cena($pdo,$blc,'Motivated Lighting','Fonte diegética','luz justificada por elementos da cena (janela, abajur)','motivated_lighting',12);
  upsert_cena($pdo,$blc,'Practical Lights','Luzes do cenário','luzes visíveis no quadro contribuindo para a exposição','practical_lights',13);
  upsert_cena($pdo,$blc,'Softbox Difuso','Suavidade','softbox grande com difusão ampla','softbox_difuso',14);
  upsert_cena($pdo,$blc,'Hard Light Direcional','Recorte marcado','luz dura com sombras bem definidas','hard_light',15);
  upsert_cena($pdo,$blc,'Gel Teal & Orange','Contraste de cor','key teal + fill/ambient orange cinematográfico','gel_teal_orange',16);
  upsert_cena($pdo,$blc,'Gel Magenta & Ciano','Cruzado colorido','preenchimentos magenta/ciano para atmosfera estilizada','gel_magenta_ciano',17);
  upsert_cena($pdo,$blc,'Chiaroscuro','Luz e sombra','composição dramaticamente contrastada ao estilo noir','chiaroscuro',18);
  upsert_cena($pdo,$blc,'Silhueta com Haze','Volumetria','silhuetas com feixes visíveis em haze','silhueta_haze',19);
  upsert_cena($pdo,$blc,'Bounce/Reflector','Rebatida','luz rebatida em superfícies/brancos','bounce_reflector',20);
  $blc=upsert_bloco($pdo,'Ambiente','emoji_objects',$tipoAba,4);
  upsert_cena($pdo,$blc,'Fogueira','Chamas dançantes','iluminação quente de fogueira com flicker','fogueira',1);
  upsert_cena($pdo,$blc,'Velas Românticas','Luz íntima tremulante','várias velas com flicker suave','velas_romanticas',2);
  upsert_cena($pdo,$blc,'Lanterna Terror','Sombras assombradas','lanterna de baixo criando sombras longas','lanterna_terror',3);
  upsert_cena($pdo,$blc,'Aurora Mágica','Luzes fantasiosas','aurora boreal tingindo o ambiente','aurora_magica',4);
  upsert_cena($pdo,$blc,'Lareira','Conforto','luz de lareira refletida no ambiente','lareira',5);
  upsert_cena($pdo,$blc,'Relâmpagos','Pulsos dramáticos','iluminação por flashes de relâmpago','relampagos',6);
  upsert_cena($pdo,$blc,'Luz de Poste','Noite urbana','poste de rua alaranjado formando halo','luz_de_poste',7);
  upsert_cena($pdo,$blc,'Farol Marinho','Feixe rotativo','feixe rotatório de farol cortando a névoa','farol_marinho',8);
  upsert_cena($pdo,$blc,'Holofote de Estádio','Alta intensidade','holofotes potentes com cones de luz','holofote_estadio',9);
  upsert_cena($pdo,$blc,'Vitrine Noturna','Reflexos','luzes de vitrine coloridas refletindo no vidro','vitrine_noturna',10);
  upsert_cena($pdo,$blc,'Janela com Sol','Feixes quentes','raios de sol entrando pela janela','janela_com_sol',11);
  upsert_cena($pdo,$blc,'Claraboia','Luz zenital difusa','claraboia ampla iluminando o interior','claraboia',12);
  upsert_cena($pdo,$blc,'Headlamp','Feixe estreito','lanterna de cabeça iluminando o caminho','headlamp',13);
  upsert_cena($pdo,$blc,'Sirenes de Emergência','Vermelho/Azul alternado','lavagem de cor de viaturas emergenciais','sirenes_emergencia',14);
  upsert_cena($pdo,$blc,'Luz de Palco','Spot teatral','spot em artista com fumaça leve','luz_de_palco',15);
  upsert_cena($pdo,$blc,'Vitral Colorido','Projeções cromáticas','luz atravessando vitrais criando manchas de cor','vitral_colorido',16);
  $blc=upsert_bloco($pdo,'Direção da Luz','north_east',$tipoAba,5);
  upsert_cena($pdo,$blc,'Frontal','Uniforme','luz frontal direta, minimiza sombras no rosto','frontal',1);
  upsert_cena($pdo,$blc,'Frontal 45°','Retrato clássico','luz frontal lateral 45° criando volume','frontal_45',2);
  upsert_cena($pdo,$blc,'Lateral 90°','Dramática','luz lateral pura com forte contraste','lateral_90',3);
  upsert_cena($pdo,$blc,'Traseira (Backlight)','Rim/silhueta','luz por trás do sujeito criando recorte','backlight',4);
  upsert_cena($pdo,$blc,'3/4 Frontal','Modelagem','luz 3/4 frontal com boa modelagem facial','tres_quartos_frontal',5);
  upsert_cena($pdo,$blc,'3/4 Traseira','Separação','luz 3/4 traseira para separação do fundo','tres_quartos_traseira',6);
  upsert_cena($pdo,$blc,'Superior','Top light','luz acima do sujeito, sombras oculares','superior',7);
  upsert_cena($pdo,$blc,'Inferior','Underlight','luz vinda de baixo, efeito inquietante','inferior',8);
  $blc=upsert_bloco($pdo,'Qualidade da Luz','scatter_plot',$tipoAba,6);
  upsert_cena($pdo,$blc,'Suave Difusa','Sombras macias','luz difusa com transições suaves','suave_difusa',1);
  upsert_cena($pdo,$blc,'Dura Recortada','Sombras nítidas','luz dura com arestas definidas','dura_recortada',2);
  upsert_cena($pdo,$blc,'Penumbrada','Mista','bordas de sombra com penumbra ampla','penumbrada',3);
  upsert_cena($pdo,$blc,'Dappled','Manchas de luz','luz salpicada passando por folhagens','dappled',4);
  upsert_cena($pdo,$blc,'Volumétrica','Feixes visíveis','luz com haze/fumaça revelando feixes','volumetrica',5);
  upsert_cena($pdo,$blc,'Caustics','Refrações aquáticas','padrões caústicos de água sobre superfícies','caustics',6);
  upsert_cena($pdo,$blc,'Specular Forte','Altos brilhos','reflexos especulares intensos','specular_forte',7);
  $blc=upsert_bloco($pdo,'Cor & Gel','palette',$tipoAba,7);
  upsert_cena($pdo,$blc,'CTO','Laranja quente','gel CTO aquecendo a luz (daylight→tungstênio)','cto',1);
  upsert_cena($pdo,$blc,'CTB','Azul frio','gel CTB esfriando a luz (tungstênio→daylight)','ctb',2);
  upsert_cena($pdo,$blc,'Plus Green','Verde para fluorescente','gel verde para casar com fluorescente','plus_green',3);
  upsert_cena($pdo,$blc,'Magenta','Correção/estilo','gel magenta neutralizando verdes ou estilizando','magenta',4);
  upsert_cena($pdo,$blc,'Âmbar','Quente suave','gel âmbar para tom aconchegante','ambar',5);
  upsert_cena($pdo,$blc,'Teal','Ciano esverdeado','gel teal para atmosfera moderna','teal',6);
  upsert_cena($pdo,$blc,'Roxo Profundo','Dramático','gel roxo para cenas estilizadas','roxo_profundo',7);
  upsert_cena($pdo,$blc,'Bicolor Warm–Cool','Contraste cromático','key quente + fill frio ou vice-versa','bicolor_warm_cool',8);
  upsert_cena($pdo,$blc,'RGB Cycling','Mudança de cor','luzes RGB alternando gradualmente','rgb_cycling',9);
  $blc=upsert_bloco($pdo,'Efeitos & Partículas','blur_on',$tipoAba,8);
  upsert_cena($pdo,$blc,'Haze Leve','Atmosfera','haze leve para dar profundidade aos feixes','haze_leve',1);
  upsert_cena($pdo,$blc,'Fumaça Densa','Drama','fumaça espessa para volumetria intensa','fumaca_densa',2);
  upsert_cena($pdo,$blc,'Poeira Suspensa','Textura','poeira iluminada em backlight','poeira_suspensa',3);
  upsert_cena($pdo,$blc,'Fog de Palco','Névoa controlada','névoa de máquina com dissipação lenta','fog_palco',4);
  upsert_cena($pdo,$blc,'Partículas em Backlight','Brilho','partículas brilhando ao contra-luz','particulas_backlight',5);
  upsert_cena($pdo,$blc,'Neve Artificial','Invernal','flakes iluminados cruzando o quadro','neve_artificial',6);
  upsert_cena($pdo,$blc,'Bolhas','Lúdico','bolhas translúcidas refletindo luz','bolhas',7);
  $blc=upsert_bloco($pdo,'Modificadores','flash_on',$tipoAba,9);
  upsert_cena($pdo,$blc,'Softbox','Difusor retangular','softbox grande para suavizar sombras','softbox',1);
  upsert_cena($pdo,$blc,'Octabox','Difusor octogonal','octabox amplo para retratos','octabox',2);
  upsert_cena($pdo,$blc,'Beauty Dish','Retrato fashion','beauty dish com difusor/grade','beauty_dish',3);
  upsert_cena($pdo,$blc,'Sombrinha Difusora','Translúcida','sombrinha branca para difundir','sombrinha_difusora',4);
  upsert_cena($pdo,$blc,'Sombrinha Rebatida','Prata/Dourada','sombrinha refletora para direção suave','sombrinha_rebatida',5);
  upsert_cena($pdo,$blc,'Grid','Direcionamento','grade para estreitar o feixe','grid',6);
  upsert_cena($pdo,$blc,'Snoot','Spot estreito','snoot para feixe circular pequeno','snoot',7);
  upsert_cena($pdo,$blc,'Flag/Gobo','Cortar luz','bandeiras/gobos para recortar e projetar padrões','flag_gobo',8);
  upsert_cena($pdo,$blc,'Difusor 1 stop','Reduz intensidade','difusor de 1 stop','difusor_1_stop',9);
  upsert_cena($pdo,$blc,'Difusor 2 stops','Mais suave','difusor de 2 stops','difusor_2_stops',10);
  $blc=upsert_bloco($pdo,'Rebatidas & Reflexões','flip_camera_android',$tipoAba,10);
  upsert_cena($pdo,$blc,'Rebatida Branca','Neutra','rebatedor branco para preenchimento suave','rebatida_branca',1);
  upsert_cena($pdo,$blc,'Rebatida Prata','Brilho','rebatedor prata para mais contraste','rebatida_prata',2);
  upsert_cena($pdo,$blc,'Rebatida Dourada','Quente','rebatedor dourado para aquecer tons de pele','rebatida_dourada',3);
  upsert_cena($pdo,$blc,'Rebatida Preta (negativa)','Aumenta contraste','floppy/negativo para puxar sombras','rebatida_preta',4);
  upsert_cena($pdo,$blc,'Bounce de Parede','Amplia fonte','luz rebatida em parede grande','bounce_parede',5);
  upsert_cena($pdo,$blc,'Bounce de Teto','Suaviza','luz rebatida no teto para wash geral','bounce_teto',6);
  $blc=upsert_bloco($pdo,'Sombras & Padrões','texture',$tipoAba,11);
  upsert_cena($pdo,$blc,'Persianas','Listras dramáticas','padrão de persianas projetado como gobo','gobo_persianas',1);
  upsert_cena($pdo,$blc,'Janela','Recortes suaves','padrão de janela definindo formas de luz','gobo_janela',2);
  upsert_cena($pdo,$blc,'Folhagens','Orgânico','padrões de folhas sobre paredes/rosto','gobo_folhagens',3);
  upsert_cena($pdo,$blc,'Grades','Geométrico','padrão de grade metálica','gobo_grades',4);
  upsert_cena($pdo,$blc,'Ondas d’Água','Caustics','padrões líquidos projetados','gobo_agua',5);
  upsert_cena($pdo,$blc,'Rosas de Luz','Artístico','padrões circulares criativos','gobo_rosas',6);
  upsert_cena($pdo,$blc,'Sombras Longas','Pôr do sol','sombras compridas enfatizando direção','sombras_longas',7);
  $pdo->commit(); echo 'Seed Iluminacao OK'; } catch(Exception $e){ $pdo->rollBack(); echo 'Erro: '.$e->getMessage(); }
?>